name: mSigsyn
channels:
- defaults
- conda-forge
- r
- bioconda
dependencies:
- python=3.6
- pip
- r-base==3.6.0
- r-ggplot2
- r-knitr
- r-kernsmooth
- r-tidyverse
- r-corrr
- r-biocmanager
- r-irkernel
- r-openssl
- r-devtools
- r-sroc
- bioconductor-trackViewer
- bioconductor-genomeinfodb
- bioconductor-genomeinfodbdata
- bioconductor-genomicranges
- bioconductor-gviz
- pip:
  - -rrequirements.txt
